songsu218/Team_OnSight_FE

public/index.html, src/App.js, src/components/Footer.jsx, src/css/SignInPage.module.css, src/pages/SignInPage.jsx
로그인 페이지 디자인
로그인 실패 시 경고 문구 생성
카카오 로그인 연동(카카오 이름, 프로필 가져오기)
로그인 버튼, 카카오 로그인 버튼 눌렀 을 때 홈으로 가기(일단 주석)
=> feat: login

src/css/SignInPage.module.css, src/pages/SignUpPage.jsx
^[a-zA-Z0-9._%+-]{2,50}$ 유효성 수정
ERD : emailId -> Id 로 수정함
=> feat: 회원가입 기능 구현

src/pages/SignUpPage.jsx
=> feat: 회원가입 기능 수정

src/css/SignUpPage.module.css, src/pages/SignUpPage.jsx
=> feat: 회원가입 기능 구현 및 코드리뷰완

src/App.js, src/css/SignInPage.module.css, src/pages/SignInPage.jsx
로그인 테스트 완료 및 로그인페이지 css와 오류 수정하였습니다.
=> feat: 로그인 테스트 완료

config/env.js, package-lock.json, package.json, src/components/RecordModal.jsx, src/css/Main.module.css, src/css/RecordModal.module.css
스와이퍼소스 써서 스와이퍼 만들었음
스와이퍼는 브레이크포인트 적용해서 기본 3개 줄어들면 2개 더 줄어들면 1개만 보이게 설정함
1개만 됐을 때 가운데 정렬됐으면 좋겠는데 이건 스와이퍼 기본 넓이를 지정해서 해야하는건지 생각은 해봤는데 적용은 안함
안에 들어가는 내용은 따로 컴포넌트 분리했음
제목은 maxLength를 10으로 해서 10자 까지만 보이게하고 그 이상이면 뒤에 말줄임표 ... 붙였음
난이도를 보여주는 홀드는 div에 백그라운드컬러 넣어서 할지 img로 넣을지 고민 중
컵 영역은 아직 개발 못해서 영역만 표시해둠
시간이 남으면 할 예정 
시간 없으면 그냥 스와이퍼 1줄 더 넣을거임
기록 추가 모달창은 부트스트랩에서 가져왔음
유튜브 보고 수정함 모달 창안에 버튼을 컴포넌트 밖으로 빼서 recordModal에 넣은거임
input 요소 있고 앞에 label 달아서 제목 붙여줬는데
input 말고 div로 만든 요소나 date-picker에도 전부 다 그냥 라벨 붙여버렸음 이래도 되는진 모르겠음 
추후 공부하거나 여쭤볼 예정 
안된다고 하시면 span 으로 바꾸고 css 수정해줘야함
날짜 선택은 react-date-picker 라이브러리로 만들었음
처음에 DD-MM-YYYY 순으로 보였는데 
dateFormat="yyyy.MM.dd" 으로 해결함
onChange랑 useState로 선택한 날짜가 표시되게 함 이건 라이브러리 기본 사용 설명에 있음
운동한 날짜를 지정하는거라 미래 날짜를 선택하면 안되므로 maxDate로 미래날짜 선택 불가능하게 함
locale = "ko" 로 영어에서 한글로 보이게 함 …
=> main ui부분만 완성

src/components/RecordModal.jsx
=> Feature/38 main1.1

src/components/Header.jsx, src/css/RecordModal.module.css
=> Feature/46 main1.2

src/App.js, src/css/App.css, src/css/MyPage.module.css, src/pages/MyPage.jsx, src/pages/SignUpPage.jsx
router 를 div로 감싸고 기존 css .mw style을 주었습니다.
mypage view 작업 중입니다.
=> feat: mypage view 작업

src/css/Header.module.css, src/css/MyPage.module.css, src/pages/MyPage.jsx
로고의 크기 및 header의 넓이 폭과 폰트 사이즈를 변경하였습니다.
=> feat: header css 수정

src/css/App.css, src/css/MyPage.module.css, src/index.js, src/pages/MyPage.jsx, src/pages/SignInPage.jsx
bootstrap css파일을 불러오는 코드가 myreset.css 파일보다 하위에 있어
_reboot.scss가 적용 되는 걸 수정하였습니다.
=> feat: _reboot.scss 우선 적용 오류 해결

public/index.html, src/components/RecordList.jsx, src/components/RecordModal.jsx, src/css/App.css, src/css/Main.module.css, src/css/RecordList.module.css, src/css/RecordModal.module.css, src/pages/Challenge.jsx
메뉴 색깔 그림판 색깔에서 수정하고
app.css에 mw 넣고 에스코어드림 폰트 추가
=> feat: main 색깔 수정 app.css 수정

src/components/RankList.jsx, src/css/Main.module.css, src/css/RankList.module.css, src/pages/Main.jsx
랭킹리스트 보여주는거랑 메인 페이지 전체적인 디자인 약간 수정
스와이퍼는 추후 더 자세하게 수정할 예정
=> Feat/73   main 1,7

src/css/CreateCrew.module.css, src/pages/CreateCrew.jsx
=> Feature/78 crew 1.2

src/components/RecordList.jsx, src/components/RecordModal.jsx, src/css/App.css, src/css/RecordList.module.css, src/css/RecordModal.module.css, src/pages/Crew.jsx
기록추가 모달 난이도 리스트랑 장소 리스트 난이도 추가박스에 스크롤 넣었고
스와이퍼에 페이지네이션 넣었습니다
=> feat: 페이지네이션 완성 모달창에 스크롤 추가

src/components/list/CrewFeedlist.jsx, src/css/Crew.module.css, src/css/CrewDetail.module.css, src/css/CrewFeedlist.module.css, src/pages/CreateCrew.jsx, src/pages/Crew.jsx, src/pages/CrewDetail.jsx
crew detail 부분 수정 및 list 추가
createcrew 수정
=> feat: 크루기능구현

src/components/RecordList.jsx, src/css/Main.module.css, src/css/Ranking.module.css, src/css/RecordList.module.css, src/pages/Main.jsx, src/pages/Ranking.jsx
메인페이지 수정이랑
랭킹페이지 분리하다가
헤더부분에 로그인 만들기 위해 임시저장
=> Feat/106   main 2.0

src/components/Header.jsx
=> Feat/113   main 2.1

src/App.js, src/css/Crew.module.css, src/css/CrewDetail.module.css, src/css/ManageCrew.module.css, src/pages/Crew.jsx, src/pages/CrewDetail.jsx, src/pages/ManageCrew.jsx, src/pages/Write.jsx
detail페이지 수정
크루생성페이지 수정
크루 관리페이지 추가
피드글쓰기페이지 추가
=> Feat : crew페이지

src/App.js, src/components/list/CrewGroupfeed.jsx, src/pages/CrewDetail.jsx, src/pages/ManageCrew.jsx, src/pages/Write.jsx
=> feat:크루기능수정

src/pages/SignInPage.jsx
카카오 로그인 부분 주석처리하고 임시로 토큰로그인 되겠끔 수정했습니다.
=> feat: 로그인부분 롤백

src/css/challengeDetail.module.css, src/pages/Challenge.jsx, src/pages/ChallengeDetail.jsx
=> feat : 스와이퍼 오류 수정 ,챌린지 일정 네비 추가

src/pages/CrewDetail.jsx, src/pages/Write.jsx
=> feat crew상세부분

src/pages/Challenge.jsx
=> feat : 오류수정

src/css/Write.module.css, src/pages/CrewDetail.jsx, src/pages/Editor.jsx, src/pages/Write.jsx
=> feat Crew - write페이지

package-lock.json, package.json
=> feat crew 기능구현

src/components/ListCard.jsx, src/components/MyPageList1.jsx, src/components/MyPageList2.jsx, src/components/list/List.jsx, src/css/RecordModal.module.css
마이페이지 기록, 챌린지 리스트 불러오는 작업을 완료하였습니다.
=> feat: 마이페이지 챌린지, 기록 작업완료

src/components/RecordList.jsx, src/components/RecordModal.jsx, src/pages/Challenge.jsx
userId랑 nick도 보내고 로그인 안 했을 시 signinpage로 보내는 기능 추가했습니다
=> feat : userId랑 nick도 보내고 로그인 안했을  시 signinpage로 보내는 기능 추가

src/components/MyPageList1.jsx, src/components/MyPageList2.jsx, src/components/MyPageList3.jsx, src/components/list/FeedList.jsx, src/components/list/List.jsx, src/components/modal/InfoModal.jsx, src/components/modal/InfoUpModal.jsx, src/components/modal/PwUpModal.jsx, src/css/FeedList.module.css, src/css/List.module.css, src/pages/MyPage.jsx, src/pages/Profile.jsx
버튼 별 모달 창 띄우기 작업 및
페이지네이션 기능과
기록, 챌린지 리스트 보기 기능 작업을 완료했습니다.
=> Feature/152 mypage1.5

src/components/challenge/ChallengeModal.jsx, src/pages/Challenge.jsx
=> feat : 중간점검

src/App.js
크루 쓰기 페이지 오류 수정
App.js -> Write.jsx삭제
=> feat:크루 오류페이지수정

src/components/CrewWrite.jsx, src/css/Write.module.css
=> feat:쓰기 페이지 수정

src/components/Header.jsx, src/components/RankList.jsx, src/components/RecordList.jsx, src/css/Header.module.css, src/store/recordStore.js, src/store/store.js
rank 페이지 백엔드 연결했습니다
record는 redux에 저장된걸로 가져왔고
userAll은 fetch로 가져왔습니다 나중에 userAll도 redux에 저장하겠습니다
=> feat : rank 페이지 백엔드 연결했습니다

src/components/MyPageList2.jsx, src/components/modal/InfoUpModal.jsx, src/components/modal/PwUpModal.jsx, src/components/modal/WithdrawalModal.jsx, src/css/MyPageInfo.module.css, src/css/PwUpModal.module.css, src/pages/Challenge.jsx, src/pages/MyPage.jsx
마이페이지 작업 완료했습니다.
각종 버그는 다른 브런치를 생성해서 작업할 예정입니다.
=> feat: 마이페이지 작업완료

src/components/modal/ChallengeModal.jsx, src/css/ChallengeModal.module.css, src/pages/Challenge.jsx
=> feat : challenge 모달 연결

src/components/RankList.jsx, src/components/RecordList.jsx
=> feat : 파일 경로 수정 썸네일 경로 수정

src/components/RecordList.jsx
=> feat : 경로 수정 2

package-lock.json, package.json, src/components/RecordModal.jsx, src/css/Search.module.css, src/pages/SearchPage.jsx, src/store/searchStore.js, src/store/store.js
웹사이트 1줄이상, 목록리스트에 소개글 2줄이상이면 말줄임표
css수정
반응형
레코드 모달 수정
기록추가생성
즐겨찾기 생성
검색 안했을 때 즐겨찾기부분 보이게 하기
리덕스로 코드 변환
즐겨찾기 제거 오류 해결
맵마크 위에 텍스트 박스 수정
=> Feature/141 search1.4

src/components/RecordList.jsx, src/css/App.css, src/css/Crew.module.css, src/css/Header.module.css, src/css/Main.module.css, src/css/RecordList.module.css, src/css/Search.module.css, src/pages/Main.jsx
=> feat: main 반응형

src/pages/Crew.jsx
지역별 필터링
지역 선택 후 검색은 지역안에서만 검색 되게 
검색어는 입력 후 엔터나 아이콘을 눌러야 검색이 되게 했습니다
=> 지역필터와  검색기능

src/css/Search.module.css, src/pages/SearchPage.jsx
상세페이지 - 기록 부분
프로필사진 가져오기 , 기록 수 가져오기
Closes #197
=> 프로필사진, 기록 수 가져오기

src/css/CrewDetail.module.css
=> feat : 크루디테일 아이콘 안 눌리던거 고침

package-lock.json, package.json, src/components/Header.jsx, src/components/modal/InfoUpModal.jsx, src/index.js, src/pages/MyPage.jsx, src/store/store.js
redux-persist를 추가하여
로그아웃 시 새로고침 할 시 데이터가 안불러와지는 부분과 로그인 미처리 되는 부분이 수정되었습니다.
=> Feature/206 redux1.0

src/pages/CrewDetail.jsx
=> feat: 크루 가입하기 작업완료

src/css/Crew.module.css, src/css/CrewFeedDetail.module.css, src/css/Search.module.css, src/pages/CrewFeedDetail.jsx, src/pages/CrewFeedEdit.jsx
=> feat : css 약간 수정, 수정 삭제 안 보이게 수정

src/components/CrewWrite.jsx, src/components/MyPageList3.jsx, src/components/list/FeedList.jsx, src/css/FeedList.module.css, src/pages/CrewDetail.jsx, src/pages/CrewFeedDetail.jsx, src/pages/CrewFeedEdit.jsx
=> feat: 조회수 작업완료

src/components/MyPageList2.jsx, src/components/MyPageList3.jsx, src/components/list/FeedList.jsx, src/components/list/List.jsx, src/css/FeedList.module.css, src/css/MyPageList1.module.css, src/pages/ChallengeDetail.jsx
=> feat: 마이페이지 수정

src/App.js, src/components/CrewGroupfeed.jsx, src/components/RecordList.jsx, src/css/Crew.module.css, src/pages/RecordDetail.jsx
=> feat : 기록디테일 불러오기만 완료

src/pages/RecordDetail.jsx
=> feat : 평균기록 추가

package-lock.json, package.json, src/css/App.css, src/css/RecordDetail.module.css, src/pages/RecordDetail.jsx
=> feat : recorddetail 페이지

src/App.js, src/components/ListCard.jsx, src/components/MyPageList4.jsx, src/components/list/List.jsx, src/pages/MyPage.jsx
=> feat:임시 마이페이지 암장즐겨찾기리스트 추가

src/css/RecordDetail.module.css, src/pages/RecordDetail.jsx
=> feat : 기록디테일 css 약간 수정

src/components/RecordList.jsx, src/components/RecordModal.jsx, src/css/RecordDetail.module.css, src/css/RecordList.module.css, src/css/RecordModal.module.css, src/pages/RecordDetail.jsx
=> feat : 메인 반응형 기록모달 css 수정

src/components/CrewGroupfeed.jsx, src/components/RecordList.jsx, src/css/App.css, src/css/Crew.module.css, src/css/CrewDetail.module.css, src/css/CrewGroupfeed.module.css, src/css/CrewHome.module.css, src/css/Header.module.css, src/css/RankList.module.css, src/css/Ranking.module.css, src/css/RecordDetail.module.css, src/pages/CrewDetail.jsx, src/pages/RecordDetail.jsx
=> feat : 랭킹 반응형

package-lock.json, package.json, src/components/Header.jsx, src/components/modal/InfoModal.jsx, src/components/modal/InfoUpModal.jsx, src/components/modal/PwUpModal.jsx, src/components/modal/WithdrawalModal.jsx, src/css/FeedList.module.css, src/css/MyPageList1.module.css, src/css/Profile.module.css, src/css/SignUpPage.module.css, src/pages/Profile.jsx, src/pages/SignInPage.jsx, src/pages/SignUpPage.jsx
로그인 할 때 토큰 쿠키에서 토큰 로컬디렉토리로 변경하였습니다.
마이페이지 > 내정보 관리에서 사용하는 모달에서 동작에 대한 경고창이 띄워지게 수정하였습니다.
=> feat: 로그인 쿠키->로컬 수정

src/components/CrewWrite.jsx, src/components/ListCard.jsx, src/components/RecordModal.jsx, src/components/list/FeedList.jsx, src/components/list/List.jsx, src/css/FeedList.module.css, src/css/List.module.css, src/css/ListCard.module.css, src/pages/CrewFeedDetail.jsx, src/pages/SearchPage.jsx
기록수 카운트
피드수 카운트
피드삭제 카운트
작업 완료했습니다.
=> feat: 기록카운트 피드카운트 피드삭제 작업완료

src/components/RankList.jsx, src/css/RankList.module.css, src/css/Ranking.module.css, src/pages/Ranking.jsx
=> feat : 랭크 페이지 수정

src/css/SignInPage.module.css, src/css/SignUpPage.module.css, src/pages/SignInPage.jsx, src/pages/SignUpPage.jsx
로그인 회원가입 css 수정
passwordVisible 설정
=> Feature/260 signup1.1

src/App.js, src/components/Header.jsx, src/components/MyPageList1.jsx, src/components/MyPageList2.jsx, src/components/MyPageList3.jsx, src/components/MyPageList4.jsx, src/pages/CrewDetail.jsx, src/pages/MyPage copy.jsx, src/pages/MyPage.jsx
=> feat: 상대프로필완료

src/components/CrewManage.jsx, src/pages/Challenge.jsx, src/pages/CreateCrew.jsx, src/pages/Crew.jsx
=> Feature/271 crewsearch1.1

src/components/Header.jsx, src/css/Header.module.css
=> feat : 햄버거 버튼 추가

src/components/RankList.jsx, src/css/CrewDetail.module.css, src/css/RankList.module.css, src/pages/CreateCrew.jsx, src/pages/CrewDetail.jsx
크루랑 랭킹에 navigate 달고 크루탈퇴하기 버튼만 만들었어요
=> feat : 크루랑 랭킹에 navigate 달고 크루탈퇴하기 버튼만 만들었어요

src/pages/CrewDetail.jsx
=> feat : 조건 추가

src/api.js, src/components/modal/ChallengeModal.jsx, src/css/ChallengeModal.module.css, src/css/challenge.module.css
=> feat : 모달 운동장소

src/components/Header.jsx, src/pages/Oauth.jsx, src/pages/SignInPage.jsx
=> feat: 로그인먼저함

src/components/CrewManage.jsx, src/components/Header.jsx, src/css/App.css, src/css/Crew.module.css, src/css/Header.module.css, src/css/RecordModal.module.css, src/pages/Crew.jsx, src/pages/CrewDetail.jsx
=> feat : 7.3 회의록에 있는 오류들 수정

src/pages/CrewDetail.jsx
=> feat: 크루 탈퇴 완료

src/css/CrewDetail.module.css, src/pages/CrewDetail.jsx, src/pages/CrewFeedDetail.jsx, src/pages/RecordDetail.jsx
=> feat: levelsum 보이게 크루장 추가
